### ISSUE TITLE
enableScrollWheelZoom and IE11

### ISSUE THREAD

**Issue by tschlarm** [Esri/bootstrap-map-js#97]
Using IE11, JSAPI3.9 and latest BootstrapMap

This is most likely an ESRI jsapi issue, but I have a map using BootstrapMap where the scrollWheelZoom is enabled. It works well until I open and new tab and tear the new tab off from the main IE11 window. Once I do that, the scrollWheelZoom on the map stops working. Seems to work fine in Chrome.

Doing the same thing on a regular webpage (say CNN.com) in IE11, the scrollwheel still works.

Just wondering if anyone else has seen this or if there is a known work around.

Thanks

**Comment by tom-1** [comment]
In IE11 v(11.0.9.9600.17728) using ESRI JS API 3.13,  encountered the same bug with the mouse zoom wheel. (works fine in FF and Chrome). The issue was caused by a high performance Logitech mouse, and having Logitech's software installed on the computer. Needed to go into Logitech's "Pointer and Scrolling Settings", and disabling the checkbox for "Enable Smooth Scrolling". When toggling this checkbox on&off a zoom bug in IE11 could consistently be reproduced and disabled.
